<?php

namespace app\api\controller;
use app\BaseController;
use think\exception\HttpResponseException;

/**
 * apiBase 相当于API模块下的公告控制器
 * 如果不需要登录场景继承我们这个控制器那么
 * 如果需要登录场景那他需要继承AuthBae
 * Class ApiBase
 * @package app\api\controller
 */
class ApiBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 抛出响应异常 在全局异常处理中继续处理
     * @param mixed ...$args
     */
    public function showJson(...$args){
        throw new HttpResponseException(showJson(...$args));
    }
}